version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: standup-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: standup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: standup-bot-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/standup?schema=public
      - PORT=3000
      - API_KEY=dev-local-key
      - DEFAULT_MENTION_POLICY=names_bold
      - DEFAULT_BUSINESS_DAYS_ONLY=true
      - LLM_DISABLED=true
      - SLACK_MODE=webhook
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm start
      "

volumes:
  postgres_data: